# This file is maintained by Azure Developer CLI, i.e. "azd"
# It allows you to run your application locally with the components it needs, like storage.
# For more information, see https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/local-setup

version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
    command: /bin/bash -c "(/opt/mssql/bin/sqlservr &) && sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -i /docker-entrypoint-initdb.d/init.sql && tail -f /dev/null"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlserver-data:
